services:
  http-server-projeto-korp:
    build: ./http-server
    container_name: http-server-projeto-korp
    networks:
      - korp-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
    - ./nginx/http-server-projeto-korp.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - http-server-projeto-korp
    networks:
      - korp-network
    restart: unless-stopped


networks:
  korp-network:
    external: true
    name: korp-network
